Explicitly import exclude/3
I sometimes get the following error:

    [PROLOG SYSTEM ERROR:  Thread 1
        trapUndefined(): undefined: function_expansion:exclude/3

    PROLOG STACK:

So make sure that exclude/3 is properly defined in the function_expansion
module.